baseurl = "https://nishanths.github.io/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Nishanth Shanmugham"
title = "Nishanth Shanmugham"
pygmentsuseclasses = true

[permalinks]
fixed = ":title/"
posts = "posts/:slug/"

[params]
Author = "Nishanth Shanmugham"
CacheBuster = true
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "The website description"
Email = "nishanths@utexas.edu"
FaviconFile = "img/leaf.ico"
GATracker = "<Google-Analyics-ID>"
GitHub = "//github.com/nishanths"
Initials = "ns" # displayed on single post page
Lang = "en"
LinkedIn = "//linkedin.com/in/nshanmugham"
Twitter = "//twitter.com/nshanmugham"
# WebfontsFile = "css/proximanova.css"
